---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: scsitteam
name: smartzone
version: 0.0.1
readme: README.md
authors:
  - Marius.rieder@scs.ch (@jiuka)
description: null
license_file: LICENSE
tags:
  - ruckus
  - smartzone
repository: https://github.com/scsitteam/ansible_scsitteam.smartzone
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/scsitteam/ansible_scsitteam.smartzone
issues: https://github.com/scsitteam/ansible_scsitteam.smartzone/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
